### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/frederick-rolfe_hadrian-the-seventh#1]
# General Issues:

- [x] Re-run `se typogrify .` and commit some of the changes (removing spaces after em-dashes).

# preface.xhtml:

- [x] Capitalize the roman numeral in the `<footer>` element ([SEMOS 8.8.5.1](https://standardebooks.org/manual/1.7.3/single-page#8.8.5.1)).

- [x] The preface contains archaic capitalization. We modernize those to standard case. Make this an [Editorial] commit.

# prologue.xhtml:

- [x] Add a language tag to <i epub:type="se:name.publication.newspaper">Neue Freie Presse</i> since it's in German.

# chapter-3.xhtml:

- [x] The page scans shows no spaces between the crosses in the second to last paragraph. Add word-joiners between the crosses so they aren't separated on smaller screens.

# chapter-4.xhtml:

- [x] Capitalize the roman numeral.

# chapter-6.xhtml:

- [ ] In the `<blockquote>`, I don't think `Middle Seat 6<abbr class="eoc">d.</abbr>` is an abbreviation. `6d` looks like an alphanumeric.

# chapter-11.xhtml:

- [x] Place the salutation and the italicized sentences in a `<header>` element.

# chapter-14.xhtml:

- [x] Add a language tag to `<i epub:type="se:name.publication.newspaper">Nouvelle Revue</i>` since it's French.

# chapter-16.xhtml:

- [x] `<abbr>nem.</abbr> <abbr class="eoc">con.</abbr>` can be simplified to `<abbr class="eoc">nem. con.</abbr>` (short for nemine contradicente).

# chapter-24.xhtml:

- [x] Add a language tag to `<b>Feliciter</b>` since it's Latin.

- [x] This chapter shows the three crosses _with spaces_ this time, but I think you should replace the spaces with word joiners to match chapter 3 and to keep the crosses from separating.

# local.css:

- [x] Replace the letter CSS with:
```
/* Letters */
[epub|type~="z3998:letter"] header{
	text-align: initial;
}

footer{
	margin-top: 1em;
	text-align: right;
}

[epub|type~="z3998:salutation"] + p,
[epub|type~="z3998:letter"] header + p{
	margin-top: 1em;
	text-indent: 0;
}

[epub|type~="z3998:sender"],
[epub|type~="z3998:salutation"],
[epub|type~="z3998:signature"]{
	font-variant: small-caps;
}

[epub|type~="z3998:postscript"]{
	margin-top: 1em;
	text-align: initial;
	text-indent: 0;
}
/* End letters */
```

- [x] The header CSS for the Prooimion can be simplified.
```
/* Subchapter headers */
[epub|type~="prologue"] header{
	font-variant: small-caps;
	margin: 1em;
	text-align: center;
}
/* End subchapter headers */
```

- [x] For styling the spacing in "Signs of Smouldering Revolt", use the following CSS so that it doesn't conflict with the header CSS.
```
/* Special datelines */
#prologue-3 p + p{
	margin-top: 1em;
}
/* End special datelines */
```

- [x] Copy and paste the dedication CSS from the manual ([SEMOS 7.3.1](https://standardebooks.org/manual/1.7.3/single-page#7.3.1))

**Comment by javamanatee** [comment]
I think I got everything, so back over to you.

**Comment by EmmaSweeney** [comment]
A few more issues:

# prologue.xhtml:

- [x] Remove the `<sup>` element.

- [x] Add language tags to `<i epub:type="se:name.publication.newspaper">Kreuzzeitung</i>` and `<i epub:type="se:name.publication.book">De Ecclesia</i>`.

# chapter-4.xhtml:

- [x] In the `<blockquote>`, `<abbr epub:type="z3998:initialism">a.d.</abbr>` should have era formatting and CSS ([SEMOS 8.9.5](https://standardebooks.org/manual/1.7.3/single-page#8.9.5)).

# chapter-11.xhtml:

- [x] In the letter, convert the single quotes around `Holiness` to double quotes.

#chapter-18.xhtml:

- [x] In `...he took his <abbr epub:type="z3998:initialism">B.A.</abbr> with Ambrose`, use semantics for academic degrees ([SEMOS 8.10.5](https://standardebooks.org/manual/1.7.3/single-page#8.10.5)).

**Comment by javamanatee** [comment]
Back to you.  Now that I see I'm missing language tags on lots of pubs, here is a list of remaining candidates.  Let me know what you think.

src/epub/text/chapter-3.xhtml:name.publication.book">Satyricon -- Latin? Or leave as is? A Latin work that looks Greek.
src/epub/text/chapter-7.xhtml:name.publication.newspaper">Il Popolo Romano  -- Italian
src/epub/text/chapter-13.xhtml:name.publication.newspaper">Vorwaerts  -- German
src/epub/text/chapter-13.xhtml:name.publication.newspaper">Éclair  -- French
src/epub/text/chapter-13.xhtml:name.publication.newspaper">La Patrie  -- French
src/epub/text/chapter-17.xhtml:name.publication.newspaper">Populo Romano  -- Italian
src/epub/text/chapter-11.xhtml:name.publication.book">Epinikia  -- Greek?
src/epub/text/prologue.xhtml:name.publication.newspaper">Pridjeprowski Krai  -- Not sure? This word only appears in this book.
src/epub/text/prologue.xhtml:name.publication.book">Encheiridion -- Greek?  An anglicized form is in M-W.

**Comment by EmmaSweeney** [comment]
> src/epub/text/chapter-3.xhtml:name.publication.book">Satyricon -- Latin? Or leave as is? A Latin work that looks Greek.

leave as is.

> src/epub/text/chapter-7.xhtml:name.publication.newspaper">Il` Popolo Romano -- Italian

Add a language tag.

> src/epub/text/chapter-13.xhtml:name.publication.newspaper">Vorwaerts -- German

Add a language tag.

> src/epub/text/chapter-13.xhtml:name.publication.newspaper">Éclair -- French

Leave as is.

> src/epub/text/chapter-13.xhtml:name.publication.newspaper">La Patrie -- French

Add a language tag.

> src/epub/text/chapter-17.xhtml:name.publication.newspaper">Populo Romano -- Italian

Add a language tag.

> src/epub/text/chapter-11.xhtml:name.publication.book">Epinikia -- Greek?

Leave as is.

> src/epub/text/prologue.xhtml:name.publication.newspaper">Pridjeprowski Krai -- Not sure? This word only appears in this book.

I don't know what language that is, so leave as is.

> src/epub/text/prologue.xhtml:name.publication.book">Encheiridion -- Greek? An anglicized form is in M-W.

Leave as is.

**Comment by javamanatee** [comment]
Ready for review.

**Comment by javamanatee** [comment]
Also forgot the collection metadata! That is in there now.
